{
  inputs,
  pkgs,
  ...
}: {
  home.packages = with pkgs; [
    inputs.self.packages.${pkgs.stdenv.hostPlatform.system}.workstation
    age
    bash-language-server
    blueutil
    cloudflared
    coreutils-prefixed
    curl
    devenv
    doctl
    fastfetch
    ffmpeg
    git-lfs
    glow
    go
    gomodifytags
    gopls
    gotests
    gotools
    htop
    impl
    jq
    jujutsu
    kubectl
    kubernetes-helm
    lua-language-server
    opencode
    osv-scanner
    pkgs."poppler-utils"
    prettier
    pkgs."phpantom-lsp"
    pyright
    ripgrep
    ruff
    silver-searcher-ng
    stylua
    switchaudio-osx
    tree
    tree-sitter
    vue-language-server
    wget
    yaml-language-server
    yt-dlp
  ];

  programs.gh.enable = true;
}
